"""Full initial schema

Revision ID: aa642a79b7ac
Revises: 
Create Date: 2026-03-25 16:02:12.533499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa642a79b7ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('round_name', sa.String(length=100), nullable=False),
    sa.Column('result', sa.Enum('PENDING', 'PASSED', 'FAILED', 'ABSENT', name='roundresult'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_rounds_application_id'), 'application_rounds', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_rounds_id'), 'application_rounds', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('related_job_id', sa.Integer(), nullable=True),
    sa.Column('related_application_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.Enum('DRIVE_OPENED', 'ROUND_RESULT', 'SHORTLISTED', 'OFFER_EXTENDED', 'GENERAL', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['related_application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('ctc', sa.Float(), nullable=True),
    sa.Column('offer_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('joining_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offer_letter_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('EXTENDED', 'ACCEPTED', 'DECLINED', 'REVOKED', name='offerstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    op.create_index(op.f('ix_offers_job_id'), 'offers', ['job_id'], unique=False)
    op.create_index(op.f('ix_offers_student_id'), 'offers', ['student_id'], unique=False)
    op.add_column('applications', sa.Column('ai_score', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('ai_rank', sa.Integer(), nullable=True))
    op.alter_column('applications', 'is_eligible',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('applications', 'eligibility_reasons',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('applications', 'applied_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('applications_student_id_fkey', 'applications', type_='foreignkey')
    op.drop_constraint('applications_resume_id_fkey', 'applications', type_='foreignkey')
    op.drop_constraint('applications_job_id_fkey', 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'resumes', ['resume_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'applications', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'applications', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_column('applications', 'eligibility_checked_at')
    op.drop_column('applications', 'match_score')
    op.drop_column('applications', 'rank_among_eligible')
    op.drop_column('applications', 'experience_match_score')
    op.drop_column('applications', 'rank')
    op.drop_column('applications', 'strengths')
    op.drop_column('applications', 'skills_match_score')
    op.drop_column('applications', 'ai_summary')
    op.drop_column('applications', 'weaknesses')
    op.drop_column('colleges', 'description')
    op.drop_column('colleges', 'created_at')
    op.drop_column('colleges', 'accreditation')
    op.drop_column('colleges', 'logo_url')
    op.drop_column('colleges', 'updated_at')
    op.drop_column('colleges', 'contact_email')
    op.drop_column('colleges', 'established_year')
    op.drop_column('colleges', 'contact_phone')
    op.add_column('jobs', sa.Column('drive_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('reporting_time', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('embedding_vector', sa.Text(), nullable=True))
    op.alter_column('jobs', 'allowed_branches',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('jobs', 'exclude_placed_students',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('jobs', 'status',
               existing_type=postgresql.ENUM('OPEN', 'CLOSED', 'DRAFT', name='jobstatus'),
               type_=sa.Enum('DRAFT', 'APPROVED', 'REJECTED', 'CLOSED', 'CANCELLED', name='drivestatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::jobstatus"))
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_jobs_title', table_name='jobs')
    op.create_index(op.f('ix_jobs_recruiter_id'), 'jobs', ['recruiter_id'], unique=False)
    op.drop_constraint('jobs_recruiter_id_fkey', 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'recruiters', ['recruiter_id'], ['id'], ondelete='CASCADE')
    op.drop_column('jobs', 'currency')
    op.drop_column('jobs', 'education_level')
    op.drop_column('jobs', 'experience_years')
    op.drop_column('jobs', 'drive_status')
    op.create_unique_constraint(None, 'placement_officers', ['user_id'])
    op.create_unique_constraint(None, 'placement_officers', ['email'])
    op.drop_constraint('placement_officers_user_id_fkey', 'placement_officers', type_='foreignkey')
    op.drop_constraint('placement_officers_college_id_fkey', 'placement_officers', type_='foreignkey')
    op.create_foreign_key(None, 'placement_officers', 'colleges', ['college_id'], ['id'])
    op.create_foreign_key(None, 'placement_officers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('placement_officers', 'phone')
    op.drop_column('placement_officers', 'updated_at')
    op.drop_column('placement_officers', 'created_at')
    op.add_column('recruiters', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('recruiters', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('recruiters', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.drop_index('ix_recruiters_company_name', table_name='recruiters')
    op.create_index(op.f('ix_recruiters_email'), 'recruiters', ['email'], unique=True)
    op.create_unique_constraint(None, 'recruiters', ['user_id'])
    op.drop_constraint('recruiters_user_id_fkey', 'recruiters', type_='foreignkey')
    op.create_foreign_key(None, 'recruiters', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('recruiters', 'company_website')
    op.drop_column('recruiters', 'created_at')
    op.drop_column('recruiters', 'updated_at')
    op.drop_column('recruiters', 'last_name')
    op.drop_column('recruiters', 'linkedin_url')
    op.drop_column('recruiters', 'first_name')
    op.drop_column('recruiters', 'phone')
    op.drop_column('recruiters', 'company_description')
    op.drop_column('recruiters', 'position')
    op.add_column('resumes', sa.Column('content_type', sa.String(length=100), nullable=False))
    op.add_column('resumes', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_resumes_student_id'), 'resumes', ['student_id'], unique=False)
    op.drop_constraint('resumes_student_id_fkey', 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_column('resumes', 'parsed_data')
    op.drop_column('resumes', 'created_at')
    op.drop_column('resumes', 'extracted_skills')
    op.drop_column('resumes', 'file_size')
    op.drop_column('resumes', 'updated_at')
    op.drop_column('resumes', 'extracted_education')
    op.drop_column('resumes', 'is_primary')
    op.drop_column('resumes', 'extracted_experience')
    op.drop_column('resumes', 'parse_status')
    op.drop_column('resumes', 'extracted_certifications')
    op.drop_column('resumes', 'mime_type')
    op.drop_column('resumes', 'parse_error')
    op.alter_column('students', 'branch',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('students', 'graduation_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('students', 'cgpa',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('students', 'is_placed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('students', 'has_backlogs',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_students_enrollment_number', table_name='students')
    op.create_unique_constraint(None, 'students', ['user_id'])
    op.drop_constraint('students_college_id_fkey', 'students', type_='foreignkey')
    op.drop_constraint('students_user_id_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'students', 'colleges', ['college_id'], ['id'])
    op.drop_column('students', 'university')
    op.drop_column('students', 'created_at')
    op.drop_column('students', 'github_url')
    op.drop_column('students', 'degree')
    op.drop_column('students', 'updated_at')
    op.drop_column('students', 'linkedin_url')
    op.drop_column('students', 'portfolio_url')
    op.drop_column('students', 'enrollment_number')
    op.drop_column('students', 'phone')
    op.drop_column('students', 'major')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.add_column('students', sa.Column('major', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('enrollment_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('portfolio_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('linkedin_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('degree', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('github_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('university', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_user_id_fkey', 'students', 'users', ['user_id'], ['id'])
    op.create_foreign_key('students_college_id_fkey', 'students', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'students', type_='unique')
    op.create_index('ix_students_enrollment_number', 'students', ['enrollment_number'], unique=True)
    op.alter_column('students', 'has_backlogs',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('students', 'is_placed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('students', 'cgpa',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('students', 'graduation_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'branch',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.add_column('resumes', sa.Column('parse_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('extracted_certifications', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('parse_status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('extracted_experience', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('extracted_education', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('resumes', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('extracted_skills', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('resumes', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('resumes', sa.Column('parsed_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.create_foreign_key('resumes_student_id_fkey', 'resumes', 'students', ['student_id'], ['id'])
    op.drop_index(op.f('ix_resumes_student_id'), table_name='resumes')
    op.drop_column('resumes', 'uploaded_at')
    op.drop_column('resumes', 'content_type')
    op.add_column('recruiters', sa.Column('position', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('recruiters', sa.Column('company_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('recruiters', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('recruiters', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('recruiters', sa.Column('linkedin_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('recruiters', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('recruiters', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('recruiters', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('recruiters', sa.Column('company_website', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'recruiters', type_='foreignkey')
    op.create_foreign_key('recruiters_user_id_fkey', 'recruiters', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'recruiters', type_='unique')
    op.drop_index(op.f('ix_recruiters_email'), table_name='recruiters')
    op.create_index('ix_recruiters_company_name', 'recruiters', ['company_name'], unique=False)
    op.drop_column('recruiters', 'is_verified')
    op.drop_column('recruiters', 'website')
    op.drop_column('recruiters', 'email')
    op.add_column('placement_officers', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('placement_officers', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('placement_officers', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'placement_officers', type_='foreignkey')
    op.drop_constraint(None, 'placement_officers', type_='foreignkey')
    op.create_foreign_key('placement_officers_college_id_fkey', 'placement_officers', 'colleges', ['college_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('placement_officers_user_id_fkey', 'placement_officers', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'placement_officers', type_='unique')
    op.drop_constraint(None, 'placement_officers', type_='unique')
    op.add_column('jobs', sa.Column('drive_status', postgresql.ENUM('DRAFT', 'APPROVED', 'REJECTED', 'CLOSED', 'CANCELLED', name='drivestatus'), server_default=sa.text("'DRAFT'::drivestatus"), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('experience_years', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('education_level', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'USD'::character varying"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('jobs_recruiter_id_fkey', 'jobs', 'recruiters', ['recruiter_id'], ['id'])
    op.drop_index(op.f('ix_jobs_recruiter_id'), table_name='jobs')
    op.create_index('ix_jobs_title', 'jobs', ['title'], unique=False)
    op.alter_column('jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'status',
               existing_type=sa.Enum('DRAFT', 'APPROVED', 'REJECTED', 'CLOSED', 'CANCELLED', name='drivestatus'),
               type_=postgresql.ENUM('OPEN', 'CLOSED', 'DRAFT', name='jobstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'OPEN'::jobstatus"))
    op.alter_column('jobs', 'exclude_placed_students',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('jobs', 'allowed_branches',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('jobs', 'embedding_vector')
    op.drop_column('jobs', 'reporting_time')
    op.drop_column('jobs', 'drive_date')
    op.add_column('colleges', sa.Column('contact_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('colleges', sa.Column('established_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('colleges', sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('colleges', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('colleges', sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('colleges', sa.Column('accreditation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('colleges', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('colleges', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('weaknesses', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('skills_match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('strengths', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('experience_match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('rank_among_eligible', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('eligibility_checked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key('applications_job_id_fkey', 'applications', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key('applications_resume_id_fkey', 'applications', 'resumes', ['resume_id'], ['id'])
    op.create_foreign_key('applications_student_id_fkey', 'applications', 'students', ['student_id'], ['id'])
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'applied_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'eligibility_reasons',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('applications', 'is_eligible',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('applications', 'ai_rank')
    op.drop_column('applications', 'ai_score')
    op.drop_index(op.f('ix_offers_student_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_job_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_application_rounds_id'), table_name='application_rounds')
    op.drop_index(op.f('ix_application_rounds_application_id'), table_name='application_rounds')
    op.drop_table('application_rounds')
    # ### end Alembic commands ###
