"""add_embedding_vector_to_jobs

Revision ID: ac026767f5eb
Revises: convert_allowed_branches_array
Create Date: 2026-04-10 16:25:05.519135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac026767f5eb'
down_revision = 'convert_allowed_branches_array'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('embedding_vector', sa.ARRAY(sa.Float()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'embedding_vector')
    # ### end Alembic commands ###
